version: '3.8'

services:
  php:
    build:
      context: .
      dockerfile: Dockerfile
    platform: linux/amd64
    container_name: php-app
    volumes:
      - ./src:/var/www/html
    ports:
      - '8000:80'
    depends_on:
      - db

  db:
    image: mysql:5.7
    platform: linux/amd64
    container_name: mysql-db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: testdb
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    volumes:
      - db_data:/var/lib/mysql

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    platform: linux/amd64
    container_name: phpmyadmin
    restart: always
    ports:
      - '8080:80'
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: root

volumes:
  db_data:
